Veewee::Session.declare({
  :cpu_count => '1',
  :memory_size => '512',
  :disk_size => '8192',
  :disk_format => 'VDI',
  :hostiocache => 'off',
  :os_type_id => 'RedHat',
  :iso_file => 'CentOS-6.5-i386-minimal.iso',
  :iso_src => 'http://yum.singlehop.com/CentOS/6.5/isos/i386/CentOS-6.5-i386-minimal.iso',
  :iso_sha256 => '3e8fb326bf389c631dcea9c16da6ebcd2c6f150d526e147c1307beb9314eb794',
  :iso_download_timeout => '1000',
  :boot_wait => '10',
  :boot_cmd_sequence => [
    '<Tab> text ks=http://%IP%:%PORT%/ks.cfg<Enter>',
  ],
  :kickstart_port => '7122',
  :kickstart_timeout => '300',
  :kickstart_file => 'ks.cfg',
  :ssh_login_timeout => '10000',
  :ssh_user => 'veewee',
  :ssh_password => 'veewee',
  :ssh_key => '',
  :ssh_host_port => '7222',
  :ssh_guest_port => '22',
  :sudo_cmd => "echo '%p'|sudo -S sh '%f'",
  :shutdown_cmd => '/sbin/halt -h -p',
  :postinstall_files => %w[../centos-postinstall.sh],
  :postinstall_timeout => '10000',
  :skip_iso_transfer => true,
})
